apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: portfolio 
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 31432
  selector:
    app: postgres
