apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: portfolio 
spec:
  clusterIP: None
  ports:
  - port: 9000
    name: api
  - port: 9001
    name: console
  selector:
    app: minio

